<!DOCTYPE html>
<html>
<head>
<title><@--ECHO title--@></title>
<style>
#container {
	box-shadow: 0px 10px 16px 0px rgba(0, 0, 0, 0.2), 0px 6px 20px 0px
		rgba(0, 0, 0, 0.19) !important;
	width: 300px;
	height: 300px;
	position: absolute;
	left: 50%;
	top: 50%;
	margin: -150px 0 0 -150px;
	border-radius: 10px 10px 0 0;
}
#title {
	text-align: center;
	background-color: #737373;
	border-radius: 10px 10px 0 0;
	font-weight: bolder;
	font-size: 16px;
	height:20px;
}
.accept_buttom{
  display:block;
  width:300px;
  height:20px;
  text-align:center;
  Text-decoration: none;
  color:black;
}

.accept_buttom.yes{
  background-color:green;
}
.accept_buttom.no{
  background-color:red;
}
</style>
</head>
<body>